# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    publishJUnitResults: false
    javaHomeOption: 'JDKVersion'
    mavenVersionOption: 'Default'
    mavenAuthenticateFeed: false
    effectivePomSkip: false
    sqMavenPluginVersionChoice: 'latest'
- bash: ls -R $(System.DefaultWorkingDirectory)
- task: AzureRmWebAppDeployment@4
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'PSL113790_ICC_Remediation_REQ000000762833(6c980470-27a0-4759-b7dc-26ed1c492299)'
    appType: 'webApp'
    WebAppName: 'k8s-cluster'
    packageForLinux: '$(System.DefaultWorkingDirectory)/**/*.jar'
